version: "3.8"

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
    networks:
      - postgres_network

  admin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80" # Expose pgAdmin port
    environment:
      PGADMIN_DEFAULT_EMAIL: 8690@holbertonstudents.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin 
    depends_on:
      - db
    networks:
      - postgres_network

networks:
  postgres_network:
    external: false  # Create a private network

volumes:
  postgres_data: